### ISSUE TITLE
Cant get the resume to build

### ISSUE THREAD

**Issue by hallzy** [philippbayer/CV#1]
Hi, I am trying to get this template to build but am having no such luck. I had a bunch of errors for fonts, then I found the fonts and the pdf builds but all the characters are just replaced with coloured square boxes.

I am trying this on Ubuntu 12.04. Just wondering if this is the same OS as what you are using, and if so, how you got it to work.

Thanks.

**Comment by hallzy** [comment]
I managed to solve the problem. Was still missing some fonts.

**Comment by philippbayer** [comment]
Great to see that this worked out by itself! Was it just these fonts ( http://sourceforge.net/projects/sourcesans.adobe/ ) or others too? It works on my Fedora, there's a tiny tiny possibility that Fedora has a font Ubuntu doesn't have

**Comment by hallzy** [comment]
I think I may have tried those but they needed building and the tool that is supposed to build them did not work for some reason. Fedora must come with some extra fonts or something like that...

I am just going to try the setup on a fresh install of ubuntu before I post what I did here just to make sure that it all works, but I did need that font, and I also needed the math font and 3 other files in a LaTeX directory.

I will post back here with my procedure for anyone else (or yourself) that may run into this same problem. Thanks for the template and setup files though :) Really helped.

**Comment by hallzy** [comment]
For Ubuntu 12.04 LTS I did:

``` bash
sudo add-apt-repository ppa:texlive-backports/ppa
sudo apt-get install texlive-full
```

Note that texlive-full takes a long time to install (I am talking a few hours). it is possible that you may be able to get it working with several smaller latex packages but I just went ahead and did everything.

Once this is done, we need the fonts... For the sake of making this simpler, I have a [folder in my repo with all the fonts](https://github.com/hallzy/dotfiles/tree/master/.fonts), and also [this folder](https://github.com/hallzy/dotfiles/tree/master/texmf/fonts/opentype) you need... copy all those to a similarly placed and named folder.

Now also get these [fonts](https://github.com/hallzy/dotfiles/tree/master/.latex-unicode-math) and then do this (assuming ~/.latex-unicode-math is the folder you put these last fonts into:

``` bash
sudo mkdir -p /usr/share/texlive/texmf-dist/tex/latex/unicode-math/
cd ~/.latex-unicode-math
sudo cp * /usr/share/texlive/texmf-dist/tex/latex/unicode-math/

sudo fc-cache -f -v
sudo -H mktexlsr
```

I believe I also needed to install php5-cli to successfully do the above, but if not then dont bother.

That should be all that is needed for ubuntu.

**Comment by philippbayer** [comment]
Thank you for these very detailed instructions! Is it OK if I add them to the README with a link to your account/name as the creator?

**Comment by hallzy** [comment]
Sure, go ahead :)

**Comment by philippbayer** [comment]
I've added it here, thank you very much: https://github.com/philippbayer/CV/blob/master/Readme.md#on-ubuntu
